config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to =>"homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/search', to: 'searchs#search'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    render :book_comments #render先にjsファイルを指定
    # redirect_to request.referer　＃非同期通信のため削除
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    #renderしたときに@bookのデータがないので@bookを定義
    @book = Book.find(params[:book_id])
    render :book_comments #render先にjsファイルを指定
    # redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する"%>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %>
      <tr>
        
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/book_comments/book_comments.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book ) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');